addSbtPlugin("com.iheart"        %% "sbt-play-swagger"      % "0.7.5-PLAY2.7")
addSbtPlugin("com.typesafe.play" % "sbt-plugin"             % "2.7.2")
addSbtPlugin("com.typesafe.sbt"  % "sbt-native-packager"    % "1.3.18")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"           % "2.0.0")
addSbtPlugin("org.scalastyle"    %% "scalastyle-sbt-plugin" % "1.0.0")
